import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBars,
  faBookmark as faBookmarkSolid,
  faChartLine,
  faCaretLeft,
  faCaretRight,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faComment,
  faCompass,
  faCopy,
  faDownload,
  faExclamation,
  faFaceMeh,
  faGear,
  faInfo,
  faLink,
  faLocationArrow,
  faLocationDot,
  faMap,
  faMinus,
  faPencil,
  faPlus,
  faSatellite,
  faScaleBalanced,
  faShareNodes,
  faSort,
  faStopwatch,
  faUser,
  faWind,
  faXmark,
  faShareFromSquare,
  faTrash,
  faFloppyDisk,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBookmark as faBookmarkRegular,
  faComment as faCommentRegular,
  faMap as faMapRegular,
  faCopy as faCopyRegular,
  faFileLines,
  faPenToSquare,
} from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faBars,
  faBookmarkSolid,
  faBookmarkRegular,
  faChartLine,
  faCaretLeft,
  faCaretRight,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faCircleInfo,
  faCheck,
  faComment,
  faCommentRegular,
  faCompass,
  faCopy,
  faCopyRegular,
  faDownload,
  faInfo,
  faExclamation,
  faFaceMeh,
  faGear,
  faLink,
  faLocationArrow,
  faLocationDot,
  faMap,
  faMapRegular,
  faMinus,
  faPencil,
  faPlus,
  faSatellite,
  faScaleBalanced,
  faShareNodes,
  faSort,
  faStopwatch,
  faUser,
  faWind,
  faXmark,
  faShareFromSquare,
  faFileLines,
  faPenToSquare,
  faTrash,
  faFloppyDisk
);

export function useIcons(app) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
